CIAcademicApp/Pages/Administrador/ConsultarDocenteAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class ConsultarDocenteAdministradorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/CrearDocente.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class CrearDocenteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/CrearEstudiante.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class CrearEstudianteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/CrearNuevoUsuarioAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class CrearNuevoUsuarioAdministradorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/EliminarUsuarioAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class EliminarUsuarioAdministradorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/EstudianteConsultarAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class EstudianteConsultarAdministradorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/UsuariosAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class UsuariosAdministradorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/Administrador/VistaAdministrador.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CIAcademicApp.Pages.Administrador
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CIAcademicApp/Pages/AsignaturasEstudiante.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class AsignaturasEstudianteModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public const string SessionKeyID = "_ID";
        public static int SessionID { get; set; }
        public DataTable TblMyCourses { get; set; }
        public void GetMyStudentCourses()
        {
            Student student = new Student();
            DataSet ds = student.MisCursos(SessionID);
            try
            {
                TblMyCourses = ds.Tables[0];
            }
            catch
            {
                TblMyCourses = new DataTable();
            }

        }
        public void OnGet()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            string S = HttpContext.Session.GetInt32(SessionKeyID).ToString();
            SessionID = int.Parse(S);
            GetMyStudentCourses();
            ViewData["TblMyCourses"] = TblMyCourses;
        }
    }
}

CIAcademicApp/Pages/AsignaturasProfesor.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class AsignaturasProfesorModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public const string SessionKeyID = "_ID";
        public static int SessionID { get; set; }
        public DataTable TblSections { get; set; }
        public void GetMySections()
        {
            Teacher teacher = new Teacher();
            DataSet ds = new DataSet();
            ds = teacher.ObtenerTodasMisSecciones(SessionID);
            try
            {
                TblSections = ds.Tables[0];
            }
            catch
            {
                TblSections = new DataTable();
            }

        }
        public void OnGet()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            string S = HttpContext.Session.GetInt32(SessionKeyID).ToString();
            SessionID = int.Parse(S);
            GetMySections();
            ViewData["TblSections"] = TblSections;
        }
    }
}

CIAcademicApp/Pages/Calificaciones.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class CalificacionesModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public const string SessionKeyID = "_ID";
        public static int SessionID { get; set; }  
        public DataTable TblCurrentQualification { get; set; }
        public void GetMyCurrentQualification()
        {
            Student student = new Student();
            DataSet ds = new DataSet();
            ds = student.MisCalificacionesActuales(SessionID);
            try
            {
                TblCurrentQualification = ds.Tables[0];
            }
            catch
            {
                TblCurrentQualification = new DataTable();
            }
            
        }
        public void OnGet()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            string S = HttpContext.Session.GetInt32(SessionKeyID).ToString();
            SessionID = int.Parse(S);
            GetMyCurrentQualification();
            ViewData["TblCurrent"] = TblCurrentQualification;
        }
    }
}

CIAcademicApp/Pages/CalificarEstudiante.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class CalificarEstudianteModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public const string SessionSectionID = "_SectionID";
        public static int StudentID { get; set; }   
        public static DataTable CourseSection { get; set; }
        public static DataTable StudentSection { get; set; }
        public static int SectionID { get; set; }
        public static int StudentQualification { get; set; }

        [BindProperty]
        [Required]
        public int Qualification { get; set; }
        public void ObtenerAsignaturaSeccion()
        {
            Teacher teacher = new Teacher();
            DataSet set  = teacher.ObtenerAsignaturaSeccion(SectionID);
            CourseSection = set.Tables[0];
        }
        public void ObtenerEstudianteEspecifico()
        {
            Teacher teacher = new Teacher();
            DataSet set = teacher.ObtenerEstudianteEspecifico(SectionID, StudentID);
            StudentSection = set.Tables[0];
        }
        public void ObtenerCalificacionEstudiante()
        {
            Teacher teacher = new Teacher();
            DataSet set = teacher.ConseguirCalificacionEstudiante(SectionID, StudentID);
            try
            {
                StudentQualification = int.Parse(set.Tables[0].Rows[0][0].ToString());
            }
            catch
            {
                StudentQualification = 0;
            }
            
        }
        public void OnGet(int ID)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            SectionID = int.Parse(HttpContext.Session.GetInt32(SessionSectionID).ToString());
            StudentID = ID; 
            ObtenerAsignaturaSeccion();
            ObtenerEstudianteEspecifico();
            ObtenerCalificacionEstudiante();
            ViewData["CourseSection"] = CourseSection;
            ViewData["StudentSection"] = StudentSection;
            ViewData["StudentQualification"] = StudentQualification;
        }
        public void OnPost()
        {
            Teacher teacher = new Teacher();
            int Equivalent = teacher.RtnEquivalent(Qualification);
            int CourseID = int.Parse(CourseSection.Rows[0][0].ToString());
            int resp = teacher.Calificar(StudentID, SectionID, CourseID, Qualification, Equivalent);
            if(resp > 0)
            {
                ViewData["Message"] = "Se ha Calificado o actualizado su calificacion al estudiante " + StudentSection.Rows[0][0].ToString();
                ViewData["CourseSection"] = CourseSection;
                ViewData["StudentSection"] = StudentSection;
                ViewData["StudentQualification"] = Qualification;
            }
            else
            {
                ViewData["CourseSection"] = CourseSection;
                ViewData["StudentSection"] = StudentSection;
                ViewData["StudentQualification"] = StudentQualification;
            }
        }
    }
}

CIAcademicApp/Pages/ConsultarAsignaturaAdministrador.cshtml.cs
using CIAcademicApp.BusinessLayer;
using CIAcademicApp.DatabaseLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class ConsultarAsignaturaAdministradorModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        [BindProperty]
        [Required]
        public int Id { get; set; }
        public async Task OnGet(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            User user = new User();
            Task<DataSet> dt = user.ObtenerAsignatura(id);
            DataSet dataSet = await dt;
            ViewData["ID"] = id;
            ViewData["KeyCourse"] = dataSet.Tables[0].Rows[0][1].ToString();
            ViewData["NameCourse"] = dataSet.Tables[0].Rows[0][2].ToString();
            ViewData["Credit"] = dataSet.Tables[0].Rows[0][3].ToString();
        }
        public async Task OnPost()
        {
            User user = new User();
            Task<int> value = user.EliminarAsignatura(Id);
            int result = await value;
            if(result == 1)
            {
                ViewData["Message"] = "Se ha eliminado la asignatura " + ViewData["KeyCourse"];
            }
            Thread.Sleep(2000);
            Response.Redirect("CrearAsignatura");
        }
    }
}

CIAcademicApp/Pages/ConsultarDocenteAdministrador.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CIAcademicApp.Pages
{
    public class ConsultarDocenteAdministradorModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public static DataSet DataSet { get; set; }
        [BindProperty]
        [Required]
        public int Id { get; set; }
        public void ObtenerUnProfesor(int id)
        {
            User user = new User();
            DataSet ds = user.ObtenerUnProfesor(id);
            DataSet = ds;

        }
        public void OnGet(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            ObtenerUnProfesor(id);
            ViewData["ID"] = id;
            ViewData["Name"] = DataSet.Tables[0].Rows[0][1];
            ViewData["LastName"] = DataSet.Tables[0].Rows[0][2];
            ViewData["Email"] = DataSet.Tables[0].Rows[0][3];
            ViewData["Asignaturas"] = DataSet.Tables[1].Rows[0][0];
            ViewData["Estudiantes"] = DataSet.Tables[2].Rows[0][0];
        }
        public async Task OnPost()
        {
            Administrator administrator = new Administrator();
            Task<int> value = administrator.EliminarPersona(Id);
            int result = await value;
            if (result == 1)
            {
                ViewData["Message"] = "Se ha eliminado el docente " + DataSet.Tables[0].Rows[0][1] + " " + DataSet.Tables[0].Rows[0][2];
            }
            Thread.Sleep(2000);
            ViewData["ID"] = Id;
            ViewData["Name"] = DataSet.Tables[0].Rows[0][1];
            ViewData["LastName"] = DataSet.Tables[0].Rows[0][2];
            ViewData["Email"] = DataSet.Tables[0].Rows[0][3];
            ViewData["Asignaturas"] = DataSet.Tables[1].Rows[0][0];
            ViewData["Estudiantes"] = DataSet.Tables[2].Rows[0][0];
            Response.Redirect("CrearDocente");
        }
    }
}

CIAcademicApp/Pages/CrearAsignatura.cshtml.cs
using CIAcademicApp.BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Linq;

namespace CIAcademicApp.Pages
{
    public class CrearAsignaturaModel : PageModel
    {
        public const string SessionKeyName = "_Name";
        public static DataTable DataTable { get; set; }
        public static bool value = false;
       
        public void ObtenerAsignaturas()
        {
            User user = new User();
            DataSet Asignatura = user.ObtenerAsignaturas();
            DataTable = Asignatura.Tables[0];
           
        }
        public async void CheckTimeOut()
        {
            if (!value)
            {
                ObtenerAsignaturas();
                value = true;
                value = await AsyncTime();
                CheckTimeOut();
            }
        }
        public void ObtenerAsignaturasFiltradas(string codigo)
        {
            if (codigo == null)
                codigo = "";
            try
            {
                ViewData["Asignaturas"] = DataTable.AsEnumerable()
               .Where(row => row.Field<string>("Name_Course")
               .ToString().ToLower()
               .Contains(codigo.ToLower()) || row.Field<string>("Key_Course").ToString().ToLower().Contains(codigo.ToLower())).CopyToDataTable();
            }
            catch
            {
                DataTable table = new DataTable();
                ViewData["Asignaturas"] = table;
            }
           
            ViewData["Iteracion"] = 1;
            ViewData["Codigo"] = codigo;
        }
        public void OnGet()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString(SessionKeyName)))
            {
                Response.Redirect("Index");
            }
            CheckTimeOut();
            ViewData["Asignaturas"] = DataTable;
            ViewData["items"] = 0;
            ViewData["Iteracion"] = 1;
            ViewData["Search"] = "";

        }
        public void OnPostChange(int iter, string search)
        {
            if (string.IsNullOrEmpty(search))
                ViewData["Asignaturas"] = DataTable;
            else
                ObtenerAsignaturasFiltradas(search);
            ViewData["Iteracion"] = iter + 1;
            ViewData["Search"] = search;
        }
        public void OnPostChangeMinus(int iter, string search)
        {
            if (string.IsNullOrEmpty(search))
                ViewData["Asignaturas"] = DataTable;
            else
                ObtenerAsignaturasFiltradas(search);
            ViewData["Iteracion"] = iter - 1;
            ViewData["Search"] = search;
        }
        public void OnPostFilter(string search)
        {
            ObtenerAsignaturasFiltradas(search);
            ViewData["Search"] = search;
            ViewData["Iteracion"] = 1;
        }
        public static Task<bool> AsyncTime()
        {
            return Task.Run( () =>
            {
                Thread.Sleep(300000);
                return false;

            });
        }

    }
}

CIAcademicApp/Pages/CrearAsignatura.cshtml
@page
@model CIAcademicApp.Pages.CrearAsignaturaModel
@using System.Data
@{
    var Asignaturas = (DataTable)ViewData["Asignaturas"];
    int Cantidad = (Asignaturas.Rows.Count % 5 > 0) ? (Asignaturas.Rows.Count / 5 + 1) : (Asignaturas.Rows.Count / 5);
    int iteracion = (int)ViewData["Iteracion"];
    int ite = iteracion - 1;
    string Search = (string)ViewData["Search"];
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login Model</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css?h=b4baa272cdf7e6fc929207f0eba1527f">
    <link rel="stylesheet" href="/assets/css/Lato.css?h=dacfec06adcdcea49cc3cdead3b85714">
    <link rel="stylesheet" href="/assets/css/Nunito.css?h=555dddb13675206f5abf5cd296b628b3">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/Animated-Typing-With-Blinking.css?h=b9f293d3fb23df4806cb012d2ed48611">
    <link rel="stylesheet" href="/assets/css/button_link.css?h=ffbc888b85647755812df45e541e8e71">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <link rel="stylesheet" href="/assets/css/ListMaterias-1.css?h=5f364738728291e9e4aa72efe2b921c7">
    <link rel="stylesheet" href="/assets/css/ListMaterias.css?h=1fe6a44da6474d6df7e0833b1703650f">
    <link rel="stylesheet" href="/assets/css/Login-Form-Basic.css?h=92bfdc06623e71c3b7773fb89801d0d0">
    <link rel="stylesheet" href="/assets/css/Search-Input-Responsive-with-Icon.css?h=c5a63853e6dd86fd9ec900eae82d3494">
</head>

<body style="font-family: Nunito, sans-serif;">
<nav class="navbar navbar-light navbar-expand-md fixed-top py-3" style="font-family: Nunito, sans-serif; font-weight: bold; background: #ffffff;">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="VistaAdministrador">
            <img src="/assets/img/CIAcademic.png?h=7b6fc02cca22ff5370162431d2f8c199" alt="">
        </a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2">
            <span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navcol-2">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link  course-pointer" aria-expanded="false" data-bs-toggle="dropdown" href="#">Perfil</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="CrearSeccion"><i class="far fa-user-circle icon-margin"></i>Secciones</a>
                        <a class="dropdown-item" href="CrearAsignatura"><i class="far fa-user-circle icon-margin"></i>Asignaturas</a>
                        <a class="dropdown-item" href="Index"><i class="far fa-user-circle icon-margin"></i>Cerrar Sesion</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class=" green-background nav-link active" href="UsuariosAdministrador">Usuarios</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<section class="profile">
    <h1 class="d-flex justify-content-center margin-heading" data-aos="fade-down" style="padding-bottom: 66px; font-family: Nunito, sans-serif; text-align: center;">Crear Asignatura</h1>
    <div class="col-md-10 offset-md-1" style="margin: 0px; margin-bottom: 28px; width: 100%;">
        <div class="card m-auto" style="max-width: 850px; border-radius: 21px; border: 3px solid rgb(0, 4, 7); width: 100%;">
            <div class="card-body flex-grow-0" style="width: 100%;">
                <form class="d-flex align-items-center" method="post">
                    <i class="fas fa-search d-none d-sm-block h4 text-body m-0"></i><input class="form-control form-control-lg flex-shrink-1 form-control-borderless" type="search" placeholder="Buscar ID" name="search" value="@Search"><button class="btn btn-success btn-lg" asp-page-handler="Filter" type="submit" style="background: #FF9F1C; font-weight: bold; border-radius: 12px; color: rgb(0, 0, 0);">Buscar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container padding-container" style="background: #CBF3F0; padding-bottom: 41px;">
        <section class="flex-column justify-content-center align-items-center" style="background: white; padding: 20px; border-radius: 15px; width: auto; height: auto;">
                @for(int i = ite * 5; i<Asignaturas.Rows.Count; i++)
                {
                    @if(i < iteracion *5)
                    {
                         <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex flex-column justify-content-center align-items-center flex-md-row background-div" style="background: #ffffff; font-family: Nunito, sans-serif; font-size: 27px; font-weight: bold; padding-bottom: 17px; width: 100%;">
                            <p class="d-flex flex-grow-1 justify-content-center align-items-center justify-content-sm-center justify-content-lg-center align-items-lg-center" style="font-family: Nunito, sans-serif; text-align: center; width: 100%; height: auto; font-size: 26px;">
                                @Asignaturas.Rows[i][1] - @Asignaturas.Rows[i][2]
                            </p>
                            <div class="d-flex d-md-flex justify-content-center" style="background: rgba(255, 159, 28, 0); width: 100%; height: auto;">
                                <a asp-page ="ConsultarAsignaturaAdministrador" asp-route-id="@Asignaturas.Rows[i][0]" class="btn btn-primary btn-project" type="button" style="background: #FF9F1C; font-family: Nunito, sans-serif; padding: 8px 40px; color: rgb(0, 0, 0); font-size: 20px; margin-left: 0px; height: auto; border-radius: 14px;">
                                    <strong>Consultar</strong><br>
                                </a>
                            </div>
                        </div>

                    }
                    @if(i == iteracion * 5 && iteracion < Cantidad)
                    {
                       <form  data-aos="fade-left" data-aos-duration="1850"  method="post" align="right">
                            <input type="hidden" value="@iteracion" name="iter"/>
                            <input type="hidden" name="search" value="@Search" />
                            <input type="submit" class="btn btn-primary btn-project" asp-page-handler="Change" value="Siguiente" style="background: #CBF3F0; border-radius: 26px; padding-bottom: 0px; color:black"/>
                        </form>
                    }
                }
                @if(iteracion > 1)
                {
                    <br />
                     <form  data-aos="fade-right" data-aos-duration="1850"  method="post" align="right">
                           <input type="hidden" value="@iteracion" name="iter"/>
                           <input type="hidden" name="search" value="@Search" />
                           <input type="submit" class="btn btn-primary btn-project" asp-page-handler="ChangeMinus" value="Anterior" style="background: #CBF3F0; border-radius: 26px; padding-bottom: 0px; color:black"/>
                     </form>
                     
               }

                @if(Asignaturas.Rows.Count == 0)
                {
                    <div class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex d-xxl-flex flex-column justify-content-center align-items-center flex-md-row background-div" style="background: #ffffff; font-family: Nunito, sans-serif; font-size: 27px; font-weight: bold; padding-bottom: 17px; width: 100%;">
                        <p class="d-flex flex-grow-1 justify-content-center align-items-center justify-content-sm-center justify-content-lg-center align-items-lg-center" style="font-family: Nunito, sans-serif; text-align: center; width: 100%; height: auto; font-size: 26px;">
                           No hay asignaturas agregada
                        </p>
                        
                    </div>
                }
            </section>
        <div class="d-flex d-md-flex justify-content-center" style="background: rgba(255, 159, 28, 0); width: 100%; height: auto;">
            <button onclick = "window.location.href = 'CrearNuevaAsignatura';" class="btn btn-primary btn-project" type="button" style="background: #FF9F1C; font-family: Nunito, sans-serif; padding: 8px 40px; color: rgb(0, 0, 0); font-size: 20px; margin-left: 0px; height: auto; border-radius: 14px; margin-top: 31px;">Crear Asignatura</button>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="/assets/js/bs-init.js?h=02a8f8d0119ea38ce4670281c1438789"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
</body>

</html>